#!/bin/bash

function running_sinks {
  pactl list sinks short | grep RUNNING | cut -f1
}

function default_sink {
  name=$(pacmd stat | grep 'Default sink name:' | awk -F ': *' '{ print $2 }')
  pactl list sinks short | fgrep "$name" | cut -f1
}

function current_volume {
	declare -i volume="$(pulsemixer --get-volume | cut -f1 -d' ')"

	if (($volume > 80)) then
		echo -n "  "
	elif (($volume > 30)) then
		echo -n "󰕾  "
	elif (($volume > 10)) then
		echo -n "󰖀 "
	elif (($volume > 0)) then
		echo -n "  "
	elif (($volume < 1)) then
		echo -n "󰝟  "
	fi
	echo "$volume%"
}

function change_volumes {
  local sinks="$1"
  for sink in $sinks; do
    pactl set-sink-volume "$sink" $change
  done
}

sinks=$(running_sinks)
if [ -z "$sinks" ]; then
  sinks=$(default_sink)
fi

change=$1
cmd=${0##*/}

if  [ $change ] ; then
  change_volumes "$sinks"
fi

current_volume "$sink"
