wallpaper {
    monitor = DP-3
    path = ~/Pictures
    fit_mode = cover
	timeout = -1
}
wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures
    fit_mode = cover
	timeout = -1
}
wallpaper {
    monitor = DVI-D-1
    path = ~/Pictures
    fit_mode = cover
	timeout = -1
}

